from fastapi import APIRouter

router = APIRouter(tags=["currencies"])

CURRENCIES = [
    {"code": "USD", "symbol": "$", "name": "US Dollar"},
    {"code": "EUR", "symbol": "€", "name": "Euro"},
    {"code": "GBP", "symbol": "£", "name": "British Pound"},
    {"code": "JPY", "symbol": "¥", "name": "Japanese Yen"},
    {"code": "CNY", "symbol": "¥", "name": "Chinese Yuan"},
    {"code": "RUB", "symbol": "₽", "name": "Russian Ruble"},
    {"code": "INR", "symbol": "₹", "name": "Indian Rupee"},
    {"code": "UZS", "symbol": "so'm", "name": "Uzbekistani Som"},
    {"code": "KZT", "symbol": "₸", "name": "Kazakhstani Tenge"},
    {"code": "UAH", "symbol": "₴", "name": "Ukrainian Hryvnia"},
    {"code": "TRY", "symbol": "₺", "name": "Turkish Lira"},
    {"code": "AED", "symbol": "د.إ", "name": "UAE Dirham"},
    {"code": "SAR", "symbol": "﷼", "name": "Saudi Riyal"},
    {"code": "QAR", "symbol": "﷼", "name": "Qatari Riyal"},
    {"code": "KWD", "symbol": "د.ك", "name": "Kuwaiti Dinar"},
    {"code": "BHD", "symbol": ".د.ب", "name": "Bahraini Dinar"},
    {"code": "OMR", "symbol": "﷼", "name": "Omani Rial"},
    {"code": "EGP", "symbol": "£", "name": "Egyptian Pound"},
    {"code": "ILS", "symbol": "₪", "name": "Israeli Shekel"},
    {"code": "CAD", "symbol": "C$", "name": "Canadian Dollar"},
    {"code": "AUD", "symbol": "A$", "name": "Australian Dollar"},
    {"code": "NZD", "symbol": "NZ$", "name": "New Zealand Dollar"},
    {"code": "CHF", "symbol": "Fr", "name": "Swiss Franc"},
    {"code": "SEK", "symbol": "kr", "name": "Swedish Krona"},
    {"code": "NOK", "symbol": "kr", "name": "Norwegian Krone"},
    {"code": "DKK", "symbol": "kr", "name": "Danish Krone"},
    {"code": "PLN", "symbol": "zł", "name": "Polish Zloty"},
    {"code": "CZK", "symbol": "Kč", "name": "Czech Koruna"},
    {"code": "HUF", "symbol": "Ft", "name": "Hungarian Forint"},
    {"code": "RON", "symbol": "lei", "name": "Romanian Leu"},
    {"code": "BGN", "symbol": "лв", "name": "Bulgarian Lev"},
    {"code": "HRK", "symbol": "kn", "name": "Croatian Kuna"},
    {"code": "GEL", "symbol": "₾", "name": "Georgian Lari"},
    {"code": "AMD", "symbol": "֏", "name": "Armenian Dram"},
    {"code": "AZN", "symbol": "₼", "name": "Azerbaijani Manat"},
    {"code": "BYN", "symbol": "Br", "name": "Belarusian Ruble"},
    {"code": "MDL", "symbol": "L", "name": "Moldovan Leu"},
    {"code": "KGS", "symbol": "с", "name": "Kyrgyzstani Som"},
    {"code": "TJS", "symbol": "SM", "name": "Tajikistani Somoni"},
    {"code": "TMT", "symbol": "T", "name": "Turkmenistani Manat"},
    {"code": "AFN", "symbol": "؋", "name": "Afghan Afghani"},
    {"code": "PKR", "symbol": "₨", "name": "Pakistani Rupee"},
    {"code": "BDT", "symbol": "৳", "name": "Bangladeshi Taka"},
    {"code": "LKR", "symbol": "₨", "name": "Sri Lankan Rupee"},
    {"code": "NPR", "symbol": "₨", "name": "Nepalese Rupee"},
    {"code": "MYR", "symbol": "RM", "name": "Malaysian Ringgit"},
    {"code": "SGD", "symbol": "S$", "name": "Singapore Dollar"},
    {"code": "THB", "symbol": "฿", "name": "Thai Baht"},
    {"code": "IDR", "symbol": "Rp", "name": "Indonesian Rupiah"},
    {"code": "PHP", "symbol": "₱", "name": "Philippine Peso"},
    {"code": "VND", "symbol": "₫", "name": "Vietnamese Dong"},
    {"code": "HKD", "symbol": "HK$", "name": "Hong Kong Dollar"},
    {"code": "TWD", "symbol": "NT$", "name": "New Taiwan Dollar"},
    {"code": "KRW", "symbol": "₩", "name": "South Korean Won"},
    {"code": "MNT", "symbol": "₮", "name": "Mongolian Tugrik"},
    {"code": "BRL", "symbol": "R$", "name": "Brazilian Real"},
    {"code": "MXN", "symbol": "MX$", "name": "Mexican Peso"},
    {"code": "ARS", "symbol": "$", "name": "Argentine Peso"},
    {"code": "CLP", "symbol": "$", "name": "Chilean Peso"},
    {"code": "COP", "symbol": "$", "name": "Colombian Peso"},
    {"code": "PEN", "symbol": "S/", "name": "Peruvian Sol"},
    {"code": "UYU", "symbol": "$U", "name": "Uruguayan Peso"},
    {"code": "ZAR", "symbol": "R", "name": "South African Rand"},
    {"code": "NGN", "symbol": "₦", "name": "Nigerian Naira"},
    {"code": "GHS", "symbol": "₵", "name": "Ghanaian Cedi"},
    {"code": "KES", "symbol": "KSh", "name": "Kenyan Shilling"},
    {"code": "TZS", "symbol": "TSh", "name": "Tanzanian Shilling"},
    {"code": "UGX", "symbol": "USh", "name": "Ugandan Shilling"},
    {"code": "ETB", "symbol": "Br", "name": "Ethiopian Birr"},
    {"code": "MAD", "symbol": "د.م.", "name": "Moroccan Dirham"},
    {"code": "DZD", "symbol": "د.ج", "name": "Algerian Dinar"},
    {"code": "TND", "symbol": "د.ت", "name": "Tunisian Dinar"},
]


@router.get("/currencies")
async def list_currencies():
    return CURRENCIES
